# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddbe3a52f18d11e400aa32fb2d39b165463fc0064e023d44dfda0aa97b2972907785c8ec00fc7357ddbede7323180eb5efb5980b604131f27d1b843384e71f2e

test:
  secret_key_base: 800706d67be2119e568a296912fbf9ddfc27454956dfb8bc40c4cf5dfa3aa7dcabbc4bcfa7e0096336670a26d0b0d7c03fda74d902de1705ec8869a22eb4cdb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
